import { TokenMarketData, Image } from 'state/nftMarket/types'

export enum PaymentCurrency {
  BNB,
  WBNB,
  CONTRACT,
}

export enum BuyingStage {
  REVIEW,
  APPROVE_AND_CONFIRM,
  CONFIRM,
  TX_CONFIRMED,
  PAYMENT_CREDIT,
  CASHBACK,
  STAKE,
}

export enum LockStage {
  ADMIN_SETTINGS,
  VAVA,
  VA,
  SETTINGS,
  UPDATE,
  DEPOSIT,
  WITHDRAW,
  MINT_NOTE,
  SPLIT_SHARES,
  CLAIM_NOTE,
  UPDATE_VP,
  AUTOCHARGE,
  PAY,
  ADMIN_WITHDRAW,
  DELETE,
  NOTIFY_PAYMENT,
  CONFIRM_NOTIFY_PAYMENT,
  DELETE_VP,
  UPDATE_PROTOCOL,
  MERGE,
  UPDATE_ACCOUNT,
  COSIGNS,
  ADD_PAID_DAYS,
  UPDATE_COSIGN,
  SPONSORS,
  ADD_SPONSORS,
  REMOVE_SPONSORS,
  VOTE_UP,
  VOTE_DOWN,
  RESET,
  CREDITOR,
  CREATE_LOCK,
  HISTORY,
  ADMINS,
  CONFIRM_ADMINS,
  CONFIRM_CREATE_LOCK,
  CONFIRM_CREDITOR,
  CONFIRM_RESET,
  CONFIRM_VAVA,
  CONFIRM_VA,
  CONFIRM_VOTE_UP,
  CONFIRM_VOTE_DOWN,
  CONFIRM_ADD_SPONSORS,
  CONFIRM_REMOVE_SPONSORS,
  CONFIRM_UPDATE_COSIGN,
  CONFIRM_ADD_PAID_DAYS,
  CONFIRM_MERGE,
  CONFIRM_UPDATE_PROTOCOL,
  CONFIRM_UPDATE_VP,
  CONFIRM_UPDATE_ACCOUNT,
  CONFIRM_PAY,
  CONFIRM_ADMIN_WITHDRAW,
  CONFIRM_DELETE,
  CONFIRM_DELETE_VP,
  CONFIRM_UPDATE,
  CONFIRM_DEPOSIT,
  CONFIRM_WITHDRAW,
  CONFIRM_MINT_NOTE,
  CONFIRM_SPLIT_SHARES,
  CONFIRM_CLAIM_NOTE,
  CONFIRM_COSIGNS,
  UPLOAD,
  TX_CONFIRMED,
}


export interface BuyNFT {
  collection: {
    address: string
    name: string
  }
  token: TokenMarketData
  name: string
  image: Image
}
