export enum LockStage {
  APPLY,
  UPDATE_AUTOCHARGE,
  UPDATE_OWNER,
  UPDATE_TOKEN_ID,
  UPDATE_BOUNTY_ID,
  UPDATE_BOUNTY,
  VOTE,
  DELETE_PROTOCOL,
  DELETE,
  WITHDRAW,
  UPDATE_COSIGN,
  UPDATE_DEV,
  UPDATE_ADMIN,
  CONFIRM_UPDATE_ADMIN,
  CONFIRM_UPDATE_DEV,
  UPDATE_DISCOUNT_DIVISOR,
  CONFIRM_UPDATE_DISCOUNT_DIVISOR,
  UPDATE_PENALTY_DIVISOR,
  CONFIRM_UPDATE_PENALTY_DIVISOR,
  UPDATE_PROTOCOL,
  ADMIN_AUTOCHARGE,
  UPDATE_PARAMETERS,
  UPDATE_DESCRIPTION,
  CONFIRM_WITHDRAW,
  CONFIRM_UPDATE_COSIGN,
  CONFIRM_UPDATE_PROTOCOL,
  CONFIRM_ADMIN_AUTOCHARGE,
  CONFIRM_UPDATE_PARAMETERS,
  CONFIRM_UPDATE_DESCRIPTION,
  CONFIRM_APPLY,
  CONFIRM_UPDATE_AUTOCHARGE,
  CONFIRM_UPDATE_OWNER,
  CONFIRM_UPDATE_TOKEN_ID,
  CONFIRM_UPDATE_BOUNTY_ID,
  CONFIRM_UPDATE_BOUNTY,
  UPDATE_TAX_CONTRACT,
  CONFIRM_UPDATE_TAX_CONTRACT,
  UPDATE_TOKEN_IDS,
  UPDATE_PROFILE_ID,
  CLAIM_NOTE,
  UPDATE_CATEGORY,
  CONFIRM_UPDATE_CATEGORY,
  UPDATE_PRICE_PER_MINUTES,
  CONFIRM_UPDATE_PRICE_PER_MINUTES,
  UPDATE_EXCLUDED_CONTENT,
  CONFIRM_UPDATE_EXCLUDED_CONTENT,
  UPDATE_WORLD_BOUNTY,
  CONFIRM_UPDATE_WORLD_BOUNTY,
  MINT_PAST_WORLD,
  CONFIRM_MINT_PAST_WORLD,
  MINT_PRESENT_WORLD,
  CONFIRM_MINT_PRESENT_WORLD,
  UPDATE_URI_GENERATOR,
  CONFIRM_UPDATE_URI_GENERATOR,
  CONFIRM_CLAIM_PENDING,
  CONFIRM_CLAIM_NOTE,
  UPDATE_TAG_REGISTRATION,
  SPONSOR_TAG,
  CLAIM_TOKEN_SPONSOR_FUND,
  UPDATE_SPONSOR_MEDIA,
  UPDATE_CODE_INFO,
  CONFIRM_UPDATE_CODE_INFO,
  CONFIRM_UPDATE_SPONSOR_MEDIA,
  CONFIRM_CLAIM_TOKEN_SPONSOR_FUND,
  CONFIRM_SPONSOR_TAG,
  CONFIRM_UPDATE_TAG_REGISTRATION,
  TRANSFER_RECEIVABLE_TO_NOTE,
  CONFIRM_TRANSFER_RECEIVABLE_TO_NOTE,
  CONFIRM_UPDATE_PROFILE_ID,
  CONFIRM_UPDATE_TOKEN_IDS,
  CONFIRM_VOTE,
  COSIGNS,
  CONFIRM_DELETE,
  CONFIRM_DELETE_PROTOCOL,
  CONFIRM_COSIGNS,
  SETTINGS,
  ADMIN_SETTINGS,
  TX_CONFIRMED,
}

export interface ARPState {
  owner: string
  bountyId: string
  profileId: string
  tokenId: string
  amountPayable: string
  amountReceivable: string
  paidPayable: string
  paidReceivable: string
  periodPayable: string
  periodReceivable: string
  startPayable: string
  startReceivable: string
  description: string
  numPeriods: string
  name: string
  symbol: string
  requestAddress: string
  requestAmount: string
  requests: string[],
  amounts: string[]
}
