export enum LockStage {
  APPLY,
  UPDATE_AUTOCHARGE,
  UPDATE_OWNER,
  UPDATE_URI_GENERATOR,
  UPDATE_BOUNTY_ID,
  VOTE,
  DELETE_PROTOCOL,
  DELETE,
  WITHDRAW,
  SPONSOR_TAG,
  MINT_EXTRA,
  UPDATE_MINT_INFO,
  UPDATE_COSIGN,
  UPDATE_PROTOCOL,
  ADMIN_AUTOCHARGE,
  UPDATE_PARAMETERS,
  UPDATE_DESCRIPTION,
  UPDATE_CATEGORY,
  BURN,
  UPDATE_PRICE_PER_MINUTE,
  UPDATE_EXCLUDED_CONTENT,
  UPDATE_DISCOUNT_DIVISOR,
  UPDATE_PENALTY_DIVISOR,
  AUTOCHARGE,
  UPDATE_DATA_KEEPER,
  TRANSFER_TO_NOTE_RECEIVABLE,
  CLAIM_NOTE,
  UPDATE_ADMIN,
  CONFIRM_UPDATE_ADMIN,
  TRANSFER_TO_NOTE_PAYABLE,
  UPDATE_TAG_REGISTRATION,
  UPDATE_SPONSOR_MEDIA,
  UPDATE_RATING_LEGEND,
  DEPOSIT_DUE,
  CONFIRM_DEPOSIT_DUE,
  CONFIRM_UPDATE_RATING_LEGEND,
  CONFIRM_UPDATE_SPONSOR_MEDIA,
  CLAIM_REVENUE_FROM_SPONSORS,
  CONFIRM_CLAIM_REVENUE_FROM_SPONSORS,
  CONFIRM_UPDATE_TAG_REGISTRATION,
  CONFIRM_CLAIM_NOTE,
  CONFIRM_TRANSFER_TO_NOTE_PAYABLE,
  CONFIRM_TRANSFER_TO_NOTE_RECEIVABLE,
  CONFIRM_UPDATE_DATA_KEEPER,
  CONFIRM_AUTOCHARGE,
  CONFIRM_UPDATE_PENALTY_DIVISOR,
  CONFIRM_UPDATE_DISCOUNT_DIVISOR,
  CONFIRM_UPDATE_EXCLUDED_CONTENT,
  CONFIRM_UPDATE_PRICE_PER_MINUTE,
  CONFIRM_BURN,
  CONFIRM_UPDATE_CATEGORY,
  CONFIRM_WITHDRAW,
  CONFIRM_UPDATE_MINT_INFO,
  CONFIRM_SPONSOR_TAG,
  CONFIRM_MINT_EXTRA,
  CONFIRM_UPDATE_COSIGN,
  CONFIRM_UPDATE_PROTOCOL,
  CONFIRM_ADMIN_AUTOCHARGE,
  CONFIRM_UPDATE_PARAMETERS,
  CONFIRM_UPDATE_DESCRIPTION,
  CONFIRM_APPLY,
  CONFIRM_UPDATE_AUTOCHARGE,
  CONFIRM_UPDATE_OWNER,
  CONFIRM_UPDATE_URI_GENERATOR,
  CONFIRM_UPDATE_BOUNTY_ID,
  CONFIRM_VOTE,
  COSIGNS,
  CONFIRM_DELETE,
  CONFIRM_DELETE_PROTOCOL,
  CONFIRM_COSIGNS,
  SETTINGS,
  ADMIN_SETTINGS,
  TX_CONFIRMED,
}

export interface ARPState {
  owner: string
  bountyId: string
  profileId: string
  tokenId: string
  amountPayable: string
  amountReceivable: string
  paidPayable: string
  paidReceivable: string
  periodPayable: string
  periodReceivable: string
  startPayable: string
  startReceivable: string
  description: string
  numPeriods: string
  name: string
  symbol: string
  requestAddress: string
  requestAmount: string
  requests: string[],
  amounts: string[]
}
